
IMAGE_ACQUISITION_PARAMS:
  CAMERA_SERIAL_NUMBERS: ['40018631', '40023151','40023153','40022761']
  FRAME_SIZE: ['960', '480']
  OUTPUT_PATH: '/home/nely/Desktop/Cedric/images/'
  BUFFERED_FRAMES: 100

FICTRAC_PARAMS:
  FICTRAC_CONFIGURATION_FILE: "/home/nely/Desktop/Cedric/fictrac/bin/config.txt"
  FICTRAC_CONSOLE_OUT_FILE: "output.txt"
  FICTRAC_BIN_PATH: "/home/nely/Desktop/Cedric/fictrac/bin/fictrac"
  FICTRAC_CAM: 40018632

ARDUINO_PARAMS:
  BAUD_RATE: 115200
  FPS: 100
  EXPOSURE_TIME: 1000

TESTING: False
